### ISSUE TITLE
request response sometimes is not xml

### ISSUE THREAD

**Issue by ukos-git** [ioistired/ps3-update-dl#4]
I get a fairly unreadable error for some of the games.

This may probably mean that there is no update available at all.

```console
$ ~/.local/bin/ps3udl -o update BLES01555
Traceback (most recent call last):
  File "/home/user/.local/bin/ps3udl", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/ps3_update_dl.py", line 190, in main
    _main()
  File "/home/user/.local/lib/python3.8/site-packages/ps3_update_dl.py", line 185, in _main
    download_updates(**kwargs, title_id=title_id)
  File "/home/user/.local/lib/python3.8/site-packages/ps3_update_dl.py", line 132, in download_updates
    (title, *_), updates = download_info(title_id)
  File "/home/user/.local/lib/python3.8/site-packages/ps3_update_dl.py", line 70, in download_info
    return parse_updates(et.fromstring(r.text))
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1321, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

Typically if you expect that the structure of the `<xml/>` content has a certain format, you need to validate the xml response before processing it.

I take the following response from the web server as an example:

```xml
<?xml version="1.0" ?>
<titlepatch status="alive" titleid="BLES01294">
	<tag name="BLES01294_T0" popup="true" signoff="true">
		<package version="01.01" size="18101584" sha1sum="8da9d20f88bf807d24863d7974383950b2b297f2" url="http://b0.ww.np.dl.playstation.net/tppkg/np/BLES01294/BLES01294_T0/2a703ec63d32a9e7/EP1004-BLES01294_00-PATCH000ULTC0108-A0101-V0100-PE.pkg" ps3_system_ver="03.6000">
			<paramsfo>
				<TITLE>Red Dead Redemption: Game of the Year Edition</TITLE>
			</paramsfo>
		</package>
	</tag>
</titlepatch>
```

A schema for validating the response via `relaxng` looks like the following:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<element name="titlepatch" xmlns="http://relaxng.org/ns/structure/1.0" datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">
  <attribute name="status"/>
  <attribute name="titleid"/>
  <element name="tag">
    <attribute name="name"/>
    <attribute name="popup">
      <data type="boolean"/>
    </attribute>
    <attribute name="signoff">
      <data type="boolean"/>
    </attribute>
    <element name="package">
      <attribute name="version"/>
      <attribute name="size">
        <data type="integer"/>
      </attribute>
      <attribute name="sha1sum">
        <data type="hexBinary"/>
      </attribute>
      <attribute name="url">
        <data type="anyURI"/>
      </attribute>
      <attribute name="ps3_system_ver"/>
      <element name="paramsfo">
        <element name="TITLE">
          <text/>
        </element>
      </element>
    </element>
  </element>
</element>
```

If you store the schema in a file next to the certificate, you can use `lxml` for validation. Here I read the xml response also from a file.

```python
>>> import lxml                                                                                                     
>>> from lxml import etree                                                                                          
>>> with open('response.rng', 'r') as fso:                                                                          
...   rng = etree.parse(fso)                                                                                        
...                                                                                                                 
>>> schema = etree.RelaxNG(rng)                                                                                     
>>> with open('response.xml', 'r') as fso:                                                                          
...   xml = fso.read()                                                                                              
...                                                                                                                 
>>> schema.validate(xml) 
True
```

using `lxml.etree` instead of `xml.etree` does not cause further problems on my side. A complete switch-over is probably recommended.

**Comment by ukos-git** [comment]
The Error with "non-parsable" xml responses should also be catched

```
    try:
        xml = et.fromstring(r.text)  # better lxml.etree.fromstring(r.content)
    except et.ParseError as err:
        logger.debug(r.text)
        logger.critical('Could not parse response. No Update available?')
        raise err 
```

**Comment by ioistired** [comment]
Why validate first? Can't we just catch parse errors where they occur now?

**Comment by ukos-git** [comment]
Catching it is possible but if you expect a certain xml response from a web server, you should validate it when you receive it. Otherwise you run into issues later in the processing and that will obfuscate the root cause of the error.

**Comment by ioistired** [comment]
I'm just thinking cause there's only two places that could go wrong, the `fromstring()` call and actually traversing it in `parse_updates()`.
