### ISSUE TITLE
Setup fails on windows due to open reading README as CP1252

### ISSUE THREAD

**Issue by IsaacShoebottom** [ioistired/ps3-update-dl#7]
![image](https://github.com/ioistired/ps3-update-dl/assets/61301629/4adb749d-42d9-4b23-8de5-ac18a8f6373c)
[cmd_2024-05-11_23.38.44_pip_errors.log](https://github.com/ioistired/ps3-update-dl/files/15284896/cmd_2024-05-11_23.38.44_pip_errors.log)

This should be as simple as specifying the encoding in the setup.py

Output as text:
PIP STDOUT
----------
Collecting ps3-update-dl
  Using cached ps3-update-dl-0.3.0.post1.tar.gz (19 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

PIP STDERR
----------
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Isaac\AppData\Local\pipx\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Isaac\AppData\Local\pipx\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Isaac\AppData\Local\pipx\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Isaac\AppData\Local\Temp\pip-build-env-iovq1lur\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Isaac\AppData\Local\Temp\pip-build-env-iovq1lur\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Isaac\AppData\Local\Temp\pip-build-env-iovq1lur\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Isaac\AppData\Local\Temp\pip-build-env-iovq1lur\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
        File "C:\Users\Isaac\scoop\apps\python311\current\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4546: character maps to <undefined>
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ioistired** [comment]
OK, I added an encoding parameter to the setup.py. That should fix it. I also uploaded a wheel to PyPI so this shouldn't be a problem in the first place anymore. Let me know if it's not fixed.
